# Use Vagrant to run a virtual machine for development and testing.
Vagrant.configure(2) do |config|
  # Use stock Debian Linux
  config.vm.box = "debian/jessie64"
  config.vm.hostname = "sovereign.local"
  config.vm.network "private_network", ip: "172.16.100.10"

  # Disable the default shared folder, use /var/www/obo-purls instead
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "..", "/var/www/obo-purls"

  # Run Ansible to provision this VM
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "site.yml"
    ansible.host_key_checking = false
    ansible.extra_vars = { ansible_ssh_user: "vagrant", testing: true }
  end
end
