idspace: EMRO
base_url: /obo/emro

term_browser: ols
example_terms:
- EMRO_0000001

products:
- emro.owl: https://raw.githubusercontent.com/uflcod/emotion-response-ontology/master/emro.owl
- emro.obo: https://raw.githubusercontent.com/uflcod/emotion-response-ontology/master/emro.obo

entries:
- exact: /emro-non-classified.owl
  replacement: https://raw.githubusercontent.com/uflcod/emotion-response-ontology/master/emro-non-classified.owl
- exact: /emro-non-classified.obo
  replacement: https://raw.githubusercontent.com/uflcod/emotion-response-ontology/master/emro-non-classified.obo
- exact: /emro-base.owl
  replacement: https://raw.githubusercontent.com/uflcod/emotion-response-ontology/master/emro-base.owl
- exact: /emro-base.obo
  replacement: https://raw.githubusercontent.com/uflcod/emotion-response-ontology/master/emro-base.obo
- exact: /emro-simple.owl
  replacement: https://raw.githubusercontent.com/uflcod/emotion-response-ontology/master/emro-simple.owl
- exact: /emro-simple.obo
  replacement: https://raw.githubusercontent.com/uflcod/emotion-response-ontology/master/emro-simple.obo

