# PURL configuration for http://purl.obolibrary.org/obo/envo

idspace: ENVO
base_url: /obo/envo

products:
- envo.owl: https://raw.githubusercontent.com/EnvironmentOntology/envo/master/envo.owl
- envo.json: https://raw.githubusercontent.com/EnvironmentOntology/envo/master/envo.json
- envo.obo: https://raw.githubusercontent.com/EnvironmentOntology/envo/master/envo.obo

term_browser: ols

entries:
- exact: /mappings/spire-mapping.ttxt
  replacement: http://purl.obolibrary.org/obo/envo/mappings/spire-mapping.tsv

- exact: /mappings/spire-mapping.txt
  replacement: http://purl.obolibrary.org/obo/envo/mappings/spire-mapping.tsv

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/EnvironmentOntology/envo/v

- prefix: /mappings/
  replacement: https://raw.githubusercontent.com/EnvironmentOntology/envo/master/mappings/

- prefix: /subsets/
  replacement: https://raw.githubusercontent.com/EnvironmentOntology/envo/master/subsets/

- prefix: /imports/
  replacement: https://raw.githubusercontent.com/EnvironmentOntology/envo/master/src/envo/imports/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/EnvironmentOntology/envo/master/
