# PURL configuration for http://purl.obolibrary.org/obo/fma

idspace: FMA
base_url: /obo/fma

products:
- fma.owl: http://purl.org/sig/ont/fma.owl
- fma.obo: http://ontologies.berkeleybop.org/fma.obo

term_browser: custom
