# PURL configuration for http://purl.obolibrary.org/obo/hom

idspace: HOM
base_url: /obo/hom

products:
- hom.owl: https://raw.githubusercontent.com/BgeeDB/homology-ontology/refs/heads/master/src/ontology/hom.owl

term_browser: ontobee
example_terms:
- HOM_0000000
