# PURL configuration for http://purl.obolibrary.org/obo/mop

idspace: MOP
base_url: /obo/mop

products:
- mop.owl: https://raw.githubusercontent.com/rsc-ontology/rxno/refs/tags/pre-odk-release/mop.owl
- mop.obo: https://raw.githubusercontent.com/rsc-ontology/rxno/refs/tags/pre-odk-release/mop.obo

term_browser: ols
example_terms:
- MOP_0000000
