# PURL configuration for http://purl.obolibrary.org/obo/oae

idspace: OAE
base_url: /obo/oae

products:
- oae.owl: https://raw.githubusercontent.com/OAE-ontology/OAE/master/oae.owl

term_browser: ontobee
example_terms:
- OAE_0000001

entries:
- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OAE&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/OAE_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=OAE&iri=http://purl.obolibrary.org/obo/OAE_0000001

- exact: /tracker
  replacement: https://github.com/OAE-ontology/OAE/issues

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/OAE-ontology/OAE/v
  tests:
  - from: /releases/2026-04-15/oae.owl
    to: https://raw.githubusercontent.com/OAE-ontology/OAE/v2026-04-15/oae.owl

- prefix: /
  replacement: https://raw.githubusercontent.com/OAE-ontology/OAE/master/
  tests:
  - from: /oae-base.owl
    to: https://raw.githubusercontent.com/OAE-ontology/OAE/master/oae-base.owl
