# PURL configuration for http://purl.obolibrary.org/obo/rex

idspace: REX
base_url: /obo/rex

products:
- rex.owl: https://github.com/cmungall/rex/raw/refs/heads/main/rex.owl
- rex.obo: https://github.com/cmungall/rex/raw/refs/heads/main/rex.obo

term_browser: ontobee
example_terms:
- REX_0000078
