# PURL configuration for http://purl.obolibrary.org/obo/rxno

idspace: RXNO
base_url: /obo/rxno

products:
- rxno.owl: https://raw.githubusercontent.com/rsc-ontology/rxno/refs/tags/pre-odk-release/rxno.owl
- rxno.obo: https://raw.githubusercontent.com/rsc-ontology/rxno/refs/tags/pre-odk-release/rxno.obo

term_browser: ols
example_terms:
- RXNO_0000000
