# PURL configuration for http://purl.obolibrary.org/obo/stato

idspace: STATO
base_url: /obo/stato

products:
- stato.owl: https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/latest_release/stato.owl
- stato.owx: https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/latest_release/stato.owx
- stato.obo: https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/latest_release/stato.obo

term_browser: ols
example_terms:
- STATO_0000001

entries:
- exact: /tracker
  replacement: https://github.com/ISA-tools/stato/issues

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/
  tests:
  - from: /releases/2025-02-23/stato.owl
    to: https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/2025-02-23/stato.owl

### Current Releases

- exact: /releases/2025-02-23/stato.owl
  replacement: https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/2025-02-23/stato.owl

- exact: /releases/2026-04-20/stato.owl
  replacement: https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/2026-04-20/stato.owl

- exact: /releases/2026-04-20/stato.obo
  replacement: https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/2026-04-20/stato.obo


### Documentation Pages and Redirects

- exact: /homepage
  replacement: http://stato-ontology.org/

- exact: /repository
  replacement: https://github.com/ISA-tools/stato